### PR TITLE
fix float64 randomizer

### LINKED ISSUE #14: ⚡ Modify `IGenerateARandomFloatInTheRangeToAndSaveItAs` method so it accept float interval
Method `IGenerateARandomFloatInTheRangeToAndSaveItAs` should not only change name, but also be modified so it returns generator func. This func should accept argument that sets rounding for output (for example, to 2 digits after dot) and return generating func that accepts left and right end of interval as float64 instead int like currently.

EDIT: Due to [this](https://github.com/pawelWritesCode/gdutils/issues/14#issuecomment-1078848557) discovery, please do not create generator func. Just create func with signature similar to:

```go
// GenerateFloat64 generates pseudo-random float64 from provided interval and save it in cache under provided cacheKey
func (apiCtx *APIContext) GenerateFloat64(from, to float64, cacheKey string) error
```

### PR DESCRIPTION
**Pull request by mikhailbuslaev**

### CODE REVIEW

**Comment by pawelWritesCode** [comment]
Related to #14

File: steps.go [hunk 1]
```diff
@@ -433,22 +433,23 @@ func (apiCtx *APIContext) IGenerateARandomIntInTheRangeToAndSaveItAs(from, to in
...
-		return fmt.Errorf("problem during generating pseudo random float, randomInt err: %w", err)
-	}
-
-	float01 := rand.Float64()
-	strFloat := fmt.Sprintf("%.2f", float01*float64(randInt))
-	floatVal, err := strconv.ParseFloat(strFloat, 64)
-	if err != nil {
-		return fmt.Errorf("problem during generating pseudo random float, parsing err: %w", err)
+func (apiCtx *APIContext) IGenerateARandomFloatInTheRangeToAndSaveItAs(from, to float64, cacheKey string) func(from, to int, cacheKey string) error {
+	return func(from, to float64, cacheKey string) error {
```
Comment (pawelWritesCode) [inline steps.go]: Hi, method signature states, that return value will be `func(from, to int, cacheKey string) error`.
Line 437 returns slightly different function `return func(from, to float64, cacheKey string) error`. This is subject to change. 

According to discussion in #14 , please try to create slightly different method, similar to:
```go
// GenerateFloat64 generates pseudo-random float64 from provided interval and save it in cache under provided cacheKey
func (apiCtx *APIContext) GenerateFloat64(from, to float64, cacheKey string) error
```

If you need any help, ask anything

**Review by pawelWritesCode — CHANGES_REQUESTED** [review]
Please see #14 discussion

**Review by pawelWritesCode — CHANGES_REQUESTED** [review]
Please, see [this](https://github.com/pawelWritesCode/gdutils/issues/14#issuecomment-1078848557) comment in #14. 

You named func very well, but full signature is still incorrect. 

Your method signature:
```go
func (apiCtx *APIContext) GenerateFloat64(from, to float64, cacheKey string) func(from, to float64, cacheKey string) error
```

is not what is expected:

```go
func (apiCtx *APIContext) GenerateFloat64(from, to float64, cacheKey string) error
```

This method should generate random float from provided float interval (`from`, `to` arguments represents interval) and save this generated value into `ApiContext` service called `Cache` under provided key (`cacheKey` argument) and that's it. 

As I linked in the beggining of this comment there is **no more need for generator func** (function that returns closure).

Also, please **do not** round generated float64 to 2nd place after dot, as you did in 442 line. Simply we want to generate random float without rounding it and save it in cache : )

File: pkg/mathutils/mathutils.go [hunk 2]
```diff
@@ -17,3 +17,11 @@ func RandomInt(from, to int) (int, error) {
 	rand.Seed(time.Now().UnixNano())
 	return rand.Intn(to-from+1) + from, nil
 }
+
+func RandomFloat64(from, to float64) (float64, error) {
```
Comment (pawelWritesCode) [inline pkg/mathutils/mathutils.go:21]: unfortunately, I checked this function and it **does not** work properly. 

`RandomFloat64(2, 2.1)` returns `0.27440765442445636` for example, but should return some random float from interval `<2, 2.1>`.

I googled [this](https://stackoverflow.com/questions/49746992/generate-random-float64-numbers-in-specific-range-using-golang) and it uses similar algorithm, your version is:
```go
from + rand.Float64() * (from - to)
``` 

but their is:
```go
from + rand.Float64() * (to - from)
```

Please try to fix it somehow. Looking forward to see new commit :)

File: pkg/mathutils/mathutils.go [hunk 3]
```diff
@@ -17,3 +17,11 @@ func RandomInt(from, to int) (int, error) {
...
+	if to < from {
+		return 0, fmt.Errorf("could not generate random float because %d is less than %d", from, to)
```
Comment (pawelWritesCode) [inline pkg/mathutils/mathutils.go:23]: Here, `%d` does not suite. As [fmt](https://pkg.go.dev/fmt) package states, 

for floats these are valid wildcards:
```
%b	decimalless scientific notation with exponent a power of two,
	in the manner of strconv.FormatFloat with the 'b' format,
	e.g. -123456p-78
%e	scientific notation, e.g. -1.234456e+78
%E	scientific notation, e.g. -1.234456E+78
%f	decimal point but no exponent, e.g. 123.456
%F	synonym for %f
%g	%e for large exponents, %f otherwise. Precision is discussed below.
%G	%E for large exponents, %F otherwise
%x	hexadecimal notation (with decimal power of two exponent), e.g. -0x1.23abcp+20
%X	upper-case hexadecimal notation, e.g. -0X1.23ABCP+20
```

Probably the best would be to use `%.2f` -  default width, precision 2.

**Review by pawelWritesCode — CHANGES_REQUESTED** [review]
